package com.jw.cloneappcarrot.model.fake

import com.jw.cloneappcarrot.model.NeighborModel

/**
 * Created by LJW on 2022/05/27.
 *
 * Description :
 */
val FakeNeighborList: List<NeighborModel> = listOf(
    NeighborModel(
        0,
        "동네질문",
        "유저1",
        "용인시 수지구",
        "소개합니다.",
        "2022-05-27 23:00",
        "image1",
        "image2",
        "image3",
        2,
        2,
    ),
    NeighborModel(
        1,
        "동네맛집",
        "유저2",
        "용인시 수지구",
        "맛집.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        3,
        "동네소식",
        "유저3",
        "용인시 수지구",
        "궁급합니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        4,
        "취미생활",
        "유저4",
        "용인시 수지구",
        "취미생활 공유합니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        5,
        "분실/실종센터",
        "유저5",
        "용인시 수지구",
        "찾습니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        6,
        "동네사건사고",
        "유저6",
        "용인시 수지구",
        "사건 발생했습니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        7,
        "해주세요",
        "유저7",
        "용인시 수지구",
        "요청드립니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        8,
        "일상",
        "유저8",
        "용인시 수지구",
        "일상 공유 합니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        9,
        "고양이",
        "유저9",
        "용인시 수지구",
        "고양이 입니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        10,
        "강아지",
        "유저2",
        "용인시 수지구",
        "강아지 입니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
    NeighborModel(
        11,
        "건강",
        "유저2",
        "용인시 수지구",
        "건강해지는 방법 공유합니다.",
        "2022-05-28 01:00",
        "image1",
        "image2",
        "image3",
        3,
        3,
    ),
)